services:
  aqua-container:
    image: aqua_local
    ports:
      - 3000:3000
      - 3600:3600
    volumes:
      - app_data:/app/data
    environment:
      - name=value
    env_file:
      - .env


volumes:
  app_data: